name: CD

on:
  push:
    branches:
      - master

jobs:
  simulate-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checa o código
        uses: actions/checkout@v2

      - name: Setup JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: '22'

      - name: Builda com Maven
        run: mvn clean install

      - name: Simula o Deploy
        run: echo "Simulação de deploy concluida!"
