name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checa o código
        uses: actions/checkout@v2

      - name: Setup JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: '22'

      - name: Builda com Maven
        run: mvn clean install