name: DISCORD

on:
  push:
    branches:
      - master

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
    - uses: Sniddl/discord-commits@v1.6
      with:
        webhook: ${{ secrets.WEBHOOK_URL }}
        template: "avatar-with-link"
        include-extras: true