name: TEST

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'adopt'
      - name: Roda os testes com Maven
        run: mvn --batch-mode --update-snapshots verify